// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function NodeStatus():Promise<string>;

export function NodeURL():Promise<string>;
