// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function NodeStatus() {
  return window['go']['main']['App']['NodeStatus']();
}

export function NodeURL() {
  return window['go']['main']['App']['NodeURL']();
}
